### ISSUE TITLE
Not running all videos in folder

### ISSUE THREAD

**Issue by vyasmuralidharan** [AiCure/open_dbm#17]
I'm having an issue with the software, where when I try to run the program on 10 videos in a folder, I only only get data for one video in the folder (and it's not even the first video in the folder). I have followed the instructions as given in the wiki/doc as well as the ones shown in the tutorial videos, and have run the program multiple times, but keep only getting data for one video in the folder. I'm not sure what is wrong here. I'd appreciate any help!

**Comment by anzarabbas** [comment]
@vyasmuralidharan thanks for brining this up; we're looking into it.

**Comment by vjbytes102** [comment]
@vyasmuralidharan 
can you please share following information so that we can look into the issue:
1. size of the folder (combined size of all 10 videos)
2. File type of videos (it should be mp4)
3. Screenshot/logs for the error you are getting in CLI.

**Comment by vyasmuralidharan** [comment]
All are .mp4 files, and combined size is 6.28GB. I didn't notice any error within the command line but I've attached a screenshot of my terminal, I think you could make better sense of it than I can. 

<img width="1439" alt="Screen Shot 2021-02-25 at 10 56 05 AM" src="https://user-images.githubusercontent.com/47041769/109180147-9543ad80-7758-11eb-9e58-3cc36fe8227c.png">
<img width="1439" alt="Screen Shot 2021-02-25 at 10 57 26 AM" src="https://user-images.githubusercontent.com/47041769/109180190-9e347f00-7758-11eb-81ad-5c88bc36c2dc.png">

**Comment by vjbytes102** [comment]
@vyasmuralidharan thank you for sharing the details.

I can not see any error except container automatically stopped during audio file processing(HNR), we faced this issue in the past as well where length of audio file was more than 18 mins. 

Can you please confirm the length of video (21761Trauma.mp4)?

**Comment by vyasmuralidharan** [comment]
It's around 10:00 minutes. Most of the videos are around that length (but there is one video that is 18:00 minutes exactly).

**Comment by vyasmuralidharan** [comment]
Hi, just checking in to see if you had found any sort of solution? Thanks!

**Comment by vjbytes102** [comment]
@vyasmuralidharan 

I looked into the issue, tried to reproduce it on my side but everything is running as expected.(video length : 18 mins)

Based on the logs and other additional information, code is breaking only for Harmonic Noise Ratio(HNR) processing, for the rest of the features execution is fine.

So, maybe it's something with your video, can not say anything until we will get an exact video to debug the issue.

**Comment by vjbytes102** [comment]
Closing the issue as it is something with your video
