### ISSUE TITLE
Video's over a certain length causes the code to end without completion.

### ISSUE THREAD

**Issue by JonBerzon** [AiCure/open_dbm#18]
We've been running into issues when attempting to process longer videos (30 minutes - 2 hours), in which the process will kill itself before completion. This leaves us with incomplete data in comparison to what we get from 12 minutes and under where we get the derived variables etc. We are unsure if this is an issue with windows, the processing power of the computer we're using, or if certain video lengths are not meant to be used on this software. I'll attach an image below showing the command prompt, and where the process gets killed. In the picture below, we attempted to run a 38-minute video with just the acoustic dbm_group.

 For extra information, the analysis is being run on a computer running an Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz with 8 GB of ram. 
![opendbm](https://user-images.githubusercontent.com/43277845/110367978-66f68580-8016-11eb-90ec-81edd0f2e756.png)

**Comment by vjbytes102** [comment]
Parsel-mouth(using to process acoustic feature) library will not process audio file > 19mins.

Please make sure video/audio length is less than 19 mins if you want acoustic features.
