### ISSUE TITLE
Trouble starting container (Windows) 

### ISSUE THREAD

**Issue by jgunstad** [AiCure/open_dbm#2]
I'm having trouble starting the container in Windows using the command listed in the wiki. 
The command reads: > docker start <CONTAINER ID>

But, I get a "syntax of the command is incorrect" message - any suggestions?  

Thank you for your help

**Comment by anzarabbas** [comment]
@jgunstad Looking into this.

**Comment by vjbytes102** [comment]
@jgunstad 

Can you please share list of all commands which you run, also share full error message text or screenshot?

I hope you are running below commands after successful installation of **opendbm docker image**.

docker run -it image_id /bin/bash
root@<CONTAINER ID>:/app# exit

docker start container_id

**Comment by jgunstad** [comment]
Apologies in advance for a delay in sending this - internet in our neighborhood is out and I’ll send ASAP

On Nov 1, 2020, at 1:26 PM, vjbytes102 <notifications@github.com> wrote:

﻿

@jgunstad<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjgunstad&data=04%7C01%7Cjgunstad%40kent.edu%7Cb5b1ee927515427a8c4208d87e93ad0d%7Ce5a06f4a1ec44d018f73e7dd15f26134%7C1%7C0%7C637398520016446026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=03jYuxvqkDfcr%2F7S7yv9fwCn5vJsqsUiEgoknRAJUmo%3D&reserved=0>

Can you please share list of all commands which you run, also share full error message text or screenshot?

I hope you are running below commands after successful installation of opendbm docker image.

docker run -it image_id /bin/bash
root@:/app# exit

docker start container_id

**Comment by jgunstad** [comment]
Sorry again for the delay - internet is now back

In trying to recreate the problem, I generated the lines below - thank you much for taking a look

JG


C:\Users\jgunstad>docker --version
Docker version 19.03.13, build 4484c46d9d

C:\Users\jgunstad>docker build --tag dbm .
[+] Building 0.1s (2/2) FINISHED
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 2B                                                                                 0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount218114631/Dockerfile: no such file or directory

C:\Users\jgunstad>docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
dbm                      latest              cfd8aacc5b8a        5 days ago          4.99GB


docker/getting-started   latest              1f32459ef038        3 months ago        26.8MB






John Gunstad, Ph.D.
329 Kent Hall Addition
Department of Psychological Sciences
Kent State University
Kent OH 44242
P: 330-672-2589
F: 330-672-3786
E: jgunstad@kent.edu<mailto:jgunstad@kent.edu>

________________________________

**Comment by vjbytes102** [comment]
@jgunstad 

I guess you forgot to add all the commands in the reply, i can not see anything specific to docker start syntax error.

Anyways based on above comment, whenever you are trying to build a new docker image for opendbm, navigate to the folder where the OpenDBM code is, otherwise build command will give you failed to read docker file.

like:  cd open_dbm

And then try to build docker image using below command.

docker build --tag dbm .

It looks like you already have a 5 days old dbm docker image but i can not see image for ubuntu and python. On >docker images , you should get below output. It should include python and ubuntu images.

> docker images
REPOSITORY   TAG       IMAGE ID       CREATED           SIZE
dbm          latest    91e593533c96   26 minutes ago    4.98GB
python       3.6       25bb503fe8c4   5 days ago        874MB
ubuntu       18.04     6526a1858e5d   3 weeks ago       64.2MB

I will suggest you to re-install opendbm images and follow all the step mentioned into the installation document specific to window's. And make sure after successful build, you should get all required images.

Note: In future, if you already have opendbm, python & ubuntu images, do not run this command(docker build --tag dbm .)

**Comment by jgunstad** [comment]
Thank you much - will give this a try

On Nov 1, 2020, at 6:42 PM, vjbytes102 <notifications@github.com> wrote:

﻿

@jgunstad<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjgunstad&data=04%7C01%7Cjgunstad%40kent.edu%7Ce7b5c994c8154af7fa8c08d87ebfc685%7Ce5a06f4a1ec44d018f73e7dd15f26134%7C1%7C0%7C637398709419829256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kDQ5hRCad7woCAxs%2FUetBNv4xwSryWUKCk04GgLXUzE%3D&reserved=0>

I guess you forgot to add all the commands in the reply, i can not see anything specific to docker start syntax error.

Anyways based on above comment, whenever you are trying to build a new docker image for opendbm, navigate to the folder where the OpenDBM code is, otherwise build command will give you failed to read docker file.

like: cd open_dbm

And then try to build docker image using below command.

docker build --tag dbm .

It looks like you already have a 5 days old dbm docker image but i can not see image for ubuntu and python. On >docker images , you should get below output. It should include python and ubuntu images.

docker images
REPOSITORY TAG IMAGE ID CREATED SIZE
dbm latest 91e593533c96 26 minutes ago 4.98GB
python 3.6 25bb503fe8c4 5 days ago 874MB
ubuntu 18.04 6526a1858e5d 3 weeks ago 64.2MB

I will suggest you to re-install opendbm images and follow all the step mentioned into the installation document specific to window's. And make sure after successful build, you should get all required images.

Note: In future, if you already have opendbm, python & ubuntu images, do not run this command(docker build --tag dbm .)
