### ISSUE TITLE
openface failing with sample data

### ISSUE THREAD

**Issue by herrington** [AiCure/open_dbm#20]
I successfully installed open_dbm on my mac (OSX 10.15.7), entered the open_dbm directory, and ran:

bash process_dbm.sh --input_path=sample_data --output_path=~

The program appeared to provide output for everything except openface-related variables.  The terminal output showed the following error:

Computing OpenFace features /app/raw_data/subj02_timepoint01.mp4 from video file
ERROR:root:Failed to run OpenFace on /app/raw_data/subj02_timepoint01.mp4
Command '['pkg/OpenFace/build/bin/FeatureExtraction', '-q', '-2Dfp', '-3Dfp', '-pdmparams', '-pose', '-aus', '-gaze', '-f', '/app/raw_data/subj02_timepoint01.mp4', '-out_dir', '/app/output/raw_variables/subj02_timepoint01/subj02_timepoint01_openface']' returned non-zero exit status 1.

I reviewed the output of the docker installation and saw no errors related to the compilation of openface programs or their dependencies (opencv, dlib).

Thanks very much - John

**Comment by vjbytes102** [comment]
@herrington Sorry for the late reply
Will it be possible for you to provide screenshot/log file for everything you are getting in CLI when you are processing the videos.

I ran the code again just now and getting all the expected results. Will suggest you to follow all the steps again, maybe something failed in between.(record the logs for installing docker image as well)

**Comment by herrington** [comment]
Thanks very much for checking this out.  I did a fresh git pull and docker build of open_dbm, and got the same error.  Attached is the terminal output during the pull and build, and the terminal output when I ran it on the sample data.  Any idea what might be happening?

Thanks again - john
[open_dcm_sample_data_output.txt](https://github.com/AiCure/open_dbm/files/6198031/open_dcm_sample_data_output.txt)
[open_dcm_build_output.txt](https://github.com/AiCure/open_dbm/files/6198032/open_dcm_build_output.txt)

**Comment by masinoa** [comment]
Resolved offline.

**Comment by adamrcobb** [comment]
I am experiencing this same issue on a Windows 10 system.  Has a work around been developed?  

Thanks,
-Adam
