### ISSUE TITLE
openDBM

### ISSUE THREAD

**Issue by Nschotschi** [AiCure/open_dbm#21]
Hello,

I just installed openDBM and run the sample_data to look at the variables and understand the results, when I realised that the values for the raw variables fac_AUXXpres and facAUXXint do not make sense. 

In the presentation it stated, that the fac_AUXXpres variable should be binary and show if the specific AU is present or not. Interestingly the value I get is either 10 or 0 which is odd. But the real problem is, that the intensity values which should be 0-5  according to the documentation do show any kind of value even up to 233. And also how is it possible, that there is an intensity value when the fac_AUXXpres variable is 0 meaning that the specific AU ist noch present.

Thanks for the help,
Nschotschi

**Comment by Nschotschi** [comment]
Hey,
ty for the quick reply. I couldn't put the original csv file unfortunatley but this is how I importat and saved the data in Excell. 
[subj01_timepoint01_facauExcell.xlsx](https://github.com/AiCure/open_dbm/files/6157830/subj01_timepoint01_facauExcell.xlsx)

I also saw later, that the number of frames varies between the files and was wondering what the timestamp variable implies because its not ordered and when you sort it with the filter its not continous.

[subj01_timepoint01_formantExcel.xlsx](https://github.com/AiCure/open_dbm/files/6157868/subj01_timepoint01_formantExcel.xlsx)

ty very much, Nschotschi

**Comment by vjbytes102** [comment]
@Nschotschi Looks like there is some issue when you imported the data into excel from csv. I will suggest you to run the code again, verify all the output from the csv file generated by the code and then directly 'save as' sample results in excel format if you want them only in excel format.

Answer to your second question, first excel file is for facial action unit extracted from video & second one is for formant freq extracted from audio, and both features have different frame per second as they are from different sources (video & audio)

**Comment by Nschotschi** [comment]
Hey, 

thx again for the quick reply. It worked for me now but I still have one question. How can it be that the fac_AUXXpres shows the value 0 while the respective fac_AUXXint variable shows an intensity.

ty Nschotschi

**Comment by vjbytes102** [comment]
@Nschotschi , we are using openface for the processing of raw videos, openface do sometimes return AU intensity where presence of action unit is 0. We are reporting raw openface signals as part of '*_facau.csv'. But for the calculation of facial expressivity('*_face_expressivity.csv') we are excluding frames where AU presence is zero.

We are providing raw openface signals in case user wants to develop new features on their own.

**Comment by Nschotschi** [comment]
Hey vjbytes102,

thanks a lot for the explanation that helped me a lot :).
