### ISSUE TITLE
Open DBM not producing Derived Variable Output for Multiple Videos in One Folder

### ISSUE THREAD

**Issue by tmeaney95** [AiCure/open_dbm#23]
**Describe the bug**
I am trying to get derived variable outputs in Excel from a folder of 10, 1-minute long videos, but when I try to run open_dbm through terminal on the whole folder, the output I get only gives me raw variables for the 4th, 7th and the 9th image. I can get a derived variable output when I only leave 1 video in the folder, but when I have all 10 videos in the folder it doesn't work. I ran the same script with the four, 5-second sample videos provided with open_dbm, and I was able to get a derived variable output that had seperate lines in excel for the four seperate videos. This is what I am hoping to get for my 10 videos, as I am currently having to analyse each video one by one and it is very time consuming. I will provide a copy of the script I am running in Terminal in the 'To Reproduce' Section.

**To Reproduce**
1. Go to 'Terminal'
2. Run script "cd ~/open_dbm-master"
3. Run pwd command to show that I am in "Users/user/open_dbm-master"
4. Run script "bash process_dbm.sh --input_path=/USers/user/Documents/1Video_Recordings/009 --output_oath=/Users/user/Docuemtns/2Extracted_Data/009
5. Outcome: no derived variables folder with excel file inside, just a raw variables folder with raw variable outputs for Image 4 (7T), Image 7 (1T) and Image 9 (2W)
<img width="833" alt="Screen Shot 2021-08-03 at 2 00 14 pm" src="https://user-images.githubusercontent.com/88133369/127955591-c7009246-54a3-4bd0-89dd-27fae1a66445.png">.

**Expected behavior**
A derived variable folder in the output folder that has an excel file with 10 lines for each of the 10 videos in the folder. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88133369/127956413-d31e72c5-9339-4623-af61-b52d3d8772cf.png)
![image](https://user-images.githubusercontent.com/88133369/127956450-a63f8015-d4b9-4dc9-8508-36d1c958d540.png)
![image](https://user-images.githubusercontent.com/88133369/127960253-09d4b38d-d0db-4e70-80b5-f97b6c10732a.png)
![image](https://user-images.githubusercontent.com/88133369/127960274-16c03f31-2554-4268-b23d-71d7aa12b32b.png)
![image](https://user-images.githubusercontent.com/88133369/127960288-f533a9af-0473-494d-8432-3adc3ef619c3.png)
![image](https://user-images.githubusercontent.com/88133369/127960304-80b7d519-e8b8-4a88-ade5-1385232ad0e3.png)
![image](https://user-images.githubusercontent.com/88133369/127960325-e201eae6-d850-4dc1-92b9-029543209509.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur, version 11.2.2
 - Browser: Chrome
 - Version: 11.2.2

**Comment by vjbytes102** [comment]
@tmeaney95 Looks like full logs are not available in the attachment when you are running bash script at folder level. It will be hard to track where library is breaking without full logs. 

Can you please share all the logs from command line on latest execution for both the cases.

- bash script execution on full folder
- bash script execution on single video(image3 (6W).mov)

**Comment by tmeaney95** [comment]
Hi @vjbytes102,

My apologies, I have attached below the screenshots of the full script logs and outcomes in finder for both of the cases you requested.

Bash script execution on full folder and outcome (only produced raw variables folders for Image 7 (1T) and Image 9 (2W) this time):

Bash scripts:
![image](https://user-images.githubusercontent.com/88133369/128120155-79734662-9913-4e9c-a1fa-1a6b7f7e54ef.png)
![image](https://user-images.githubusercontent.com/88133369/128120165-50cbbc1b-69fd-4750-90b7-904305c9cff9.png)
![image](https://user-images.githubusercontent.com/88133369/128120184-733f6438-e68d-4628-820f-11a8f1ef0b5a.png)
![image](https://user-images.githubusercontent.com/88133369/128120196-6fd4aed1-d19a-4a01-ae30-97e4a8a1ad7e.png)
![image](https://user-images.githubusercontent.com/88133369/128120207-a557ca3b-3ba0-4f26-bd06-5dcca57809f6.png)
![image](https://user-images.githubusercontent.com/88133369/128120213-db4e4a35-e033-4ecf-884b-18cd37fb25f3.png)
![image](https://user-images.githubusercontent.com/88133369/128120233-e755688f-1413-499d-b089-7dcba2d63cf3.png)
![image](https://user-images.githubusercontent.com/88133369/128120244-e8603c49-61d7-4b8b-8445-6e88ecbe807a.png)
![image](https://user-images.githubusercontent.com/88133369/128120254-a53bf5ed-6d95-4b96-8a48-f8e158922f54.png)

Folder drawn from and folder produced in finder:
![image](https://user-images.githubusercontent.com/88133369/128121507-9dbfc55a-4cfb-49b2-9805-3a8aea0aac9b.png)
![image](https://user-images.githubusercontent.com/88133369/128120269-9c83234d-4da4-4673-b143-48d86de8286a.png)


Bash scrip execution on single video (Image 3 (6W).mov) and outcome:

Scripts:
![image](https://user-images.githubusercontent.com/88133369/128120656-1aa966fc-5d09-43fd-93ec-dc0499156f8a.png)
![image](https://user-images.githubusercontent.com/88133369/128120671-67e271f3-1923-483e-bbf2-b1c9540df15b.png)
![image](https://user-images.githubusercontent.com/88133369/128120919-916907a3-a8c0-424b-9502-f6cdacea6021.png)
![image](https://user-images.githubusercontent.com/88133369/128121208-f9b35d07-7436-42ec-8fe0-199f9dec5754.png)

Folder drawn from and folder produced in finder:
![image](https://user-images.githubusercontent.com/88133369/128121269-ab05e045-1bfd-4931-8642-076057161b47.png)
![image](https://user-images.githubusercontent.com/88133369/128121323-58c52ab3-5e1d-4af7-a00c-b4afddabc4fb.png)

Let me know if you need further information.

Kind Regards,

Tomas

**Comment by vjbytes102** [comment]
@tmeaney95 If raw videos are not in mp4 file format then as per logic, open_dbm pipeline will convert it in mp4 file format, and as per logs , looks like there is some issue with conversion of video "image 4 (7T).mov". (maybe video is corrupted) Container processing somehow stops while converting "image 4 (7T).mov"  to "image 4 (7T).mp4".

Can you please check "image 4 (7T).mov"  if there is any issue with this video?

I will suggest below
- Remove this particular video(image 4 (7T).mov) from the directory and then run bash script on full folder.
- Also, if possible run bash script execution on single video(image4 (7T).mov) to investigate it further. (if above execution is not successful) 

Let me know if it's not working. We can have a quick working session on zoom.

**Comment by tmeaney95** [comment]
@vjbytes102 I ran both scripts you suggested and checked the video. When I ran the script without video (Image 4 (7T).mov) in the directory, I still got a similar sort of output, with only raw variable outputs being provided for image 7 (1T) and Image 9 (2W). I have attached screenshots of the input and output directory as well as the terminal log below:

Directories:
![image](https://user-images.githubusercontent.com/88133369/128439175-378f8d91-f0f6-44fa-92da-2c3e6e2d5f86.png)
![image](https://user-images.githubusercontent.com/88133369/128439206-3ba62856-f0ab-43c8-9198-94f8dc3c40f7.png)

Terminal Log:
![image](https://user-images.githubusercontent.com/88133369/128439232-91876705-3669-4c6f-922c-2daca1476cac.png)
![image](https://user-images.githubusercontent.com/88133369/128439219-fc24c149-2bab-42fa-ab73-86bea5df5ae5.png)
![image](https://user-images.githubusercontent.com/88133369/128439238-b4b73ebb-095e-44a6-9136-172d62d5275b.png)
![image](https://user-images.githubusercontent.com/88133369/128439250-bedebe7d-89d6-44f6-bbcf-59478c1f3d79.png)
![image](https://user-images.githubusercontent.com/88133369/128439260-55608f7b-c153-456a-ac91-10494de1c0df.png)
![image](https://user-images.githubusercontent.com/88133369/128439270-e06b4e4e-03eb-46e8-b8c1-319d4dd17eff.png)
![image](https://user-images.githubusercontent.com/88133369/128439282-96c89bac-dafa-4f5f-aeae-fe8ecdfb70d2.png)
![image](https://user-images.githubusercontent.com/88133369/128439474-6f9589cb-1723-4902-9c71-7497cd874a07.png)

I had already run the script on video(Image 4 (7T).mov) individually and got a derived variable output for it, but I ran it again and also checked the video. When I checked the video (Image 4 7T), it was not corrupted and played through just fine. When I ran the script again I got the same derived variable output for the individual video. I have attached the input and output directories as well as the terminal log below.

Directories:
![image](https://user-images.githubusercontent.com/88133369/128439492-019c09a2-03cc-4f0d-a0a8-46f5d36b16de.png)
![image](https://user-images.githubusercontent.com/88133369/128439507-8058b89a-526d-4ce1-988e-5572c2b07a4a.png)

Terminal Log:
![image](https://user-images.githubusercontent.com/88133369/128439517-df71c9b6-0199-4212-b37d-208fd01eeedb.png)
![image](https://user-images.githubusercontent.com/88133369/128439535-f808e9a3-0bcb-49c1-9e23-bbe596135684.png)
![image](https://user-images.githubusercontent.com/88133369/128439546-e37bf41e-464a-4769-a8e6-0511f86a86cd.png)
![image](https://user-images.githubusercontent.com/88133369/128439918-d34a5a5d-10ba-42f1-a27c-6f28f27463ba.png)

I would definitely be interested in having a zoom meeting so we can get to the bottom of this issue. What day/time in the coming week would work for you?

**Comment by tmeaney95** [comment]
The input directory for the individual video (didn't seem to download in my last message)
![image](https://user-images.githubusercontent.com/88133369/128440016-39e48ec8-1744-495f-adc5-773539aeeff6.png)

**Comment by tmeaney95** [comment]
and for the script without video (Image 4 (7T)
![image](https://user-images.githubusercontent.com/88133369/128440174-8b729383-ebb3-456b-b7c3-2cfb106b002d.png)

**Comment by anzarabbas** [comment]
Hey @tmeaney95 seems like we're still stuck on this––shoot me an email at anzar@anzarabbas.com and we will scheduled a video call to troubleshoot. Cheers.

**Comment by vjbytes102** [comment]
It was docker container volume issue (Default size for docker container is 10gb. ). Increase container volume to fix it.

Closing this issue.

**Comment by masinoa** [comment]
Issue resolved as a docker container volume size parameter setting.
