### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by yikangguo** [AiCure/open_dbm#24]
Hi,

I just installed the docker and built a container on Windows following the instruction in the Wiki documents. When I run the process_data.py, I got this:

root@4f8a1641c0a3:/app# python3 process_data.py --input_path sample_data --output_path sample_output --dbm_group facial --tr on

Traceback (most recent call last):
  File "process_data.py", line 210, in <module>
    s_config = config_reader.ConfigReader()
  File "/app/dbm_lib/config/config_reader.py", line 26, in __init__
    config = yaml.load(ymlfile)
TypeError: load() missing 1 required positional argument: 'Loader'

Could you help me with this?
Thanks

**Comment by Roland-Hart** [comment]
Hi @yikangguo, we were able to get OpenFace running again using the attached code. 

The attached replaces "config = yaml.load(ymlfile)" with "config = yaml.load(ymlfile,Loader=yaml.loader.BaseLoader)" in all three scripts within the config folder and allows it to work with the updated version of Python Docker is now running. To get it working on our machines we also had to rebuild the Docker images. 

[config.zip](https://github.com/AiCure/open_dbm/files/7455956/config.zip)

Hope this helps

**Comment by liuzj09** [comment]
Hi @Roland-Hart,

I ran into the same issues as you guys. But I still couldn't get OpenFace running with your zip file. Did you just replace the config folder under dmb_lib? You said we had to rebuild our Docker images as well. I was wondeirng how to do that?

Thanks!!

**Comment by anzarabbas** [comment]
Hi all, just letting you know @vjbytes102 is looking into this! Will get back to you soon. –Anzar

**Comment by liuzj09** [comment]
Hi @anzarabbas,

I was wondering if you have looked into the problem and found out potential solutions?

Thanks!

**Comment by smithe36** [comment]
Hello, 
I am also encountering this issue, TypeError: load() missing 1 required positional argument: 'Loader'
Please let me know how I may resolve this. 
Thank you!
Emma

**Comment by vjbytes102** [comment]
@smithe36 @liuzj09 

Sorry for the late reply. Added the fix to resolve this issue. Clone the latest code & rebuild the Docker images.

Let me know if you still face any issue

**Comment by vjbytes102** [comment]
closing this issue...

**Comment by smithe36** [comment]
Thank you! It is working for me now ☺
