### ISSUE TITLE
OpenDBM web documentation

### ISSUE THREAD

**Issue by mfaisyal** [AiCure/open_dbm#28]
### 💡 The feature, motivation and pitch

It would be great if we can access web documentation for detail information about installation, usage, api and so on. It will gives community about the API details such as arguments, type of args, expected output and so on.

### Alternatives

Separate documentation site other than github readme.md which also have a structured informations for easier navigation

**Comment by anzarabbas** [comment]
Hey bud, you can check out the documentation in the git wiki and see if that’s helpful. 

Anzar
