### ISSUE TITLE
[New Feature]  Visualization Analysis Tool

### ISSUE THREAD

**Issue by CarlaFloricel** [AiCure/open_dbm#35]
### 💡 The feature, motivation and pitch

First version of a visualization analysis tool that will visualize OpenDBM output data and runs on localhost (not an API).
The tool will run via react app and will provide insight into both cohort (multiple) and individual videos using derived and raw biomarker variables. 

This will include
1. Front end
2. Back end 
3.  Documents to iterate on with community

**Comment by ADParedes** [comment]
https://github.com/AiCure/open_dbm/pull/37

**Comment by ADParedes** [comment]
Version 1 of an OpenDBM Data Visualization Interface has been released.  Next step is to provide installation instructions.
