### ISSUE TITLE
sample data run issue

### ISSUE THREAD

**Issue by joelgthomas** [AiCure/open_dbm#5]
Hello, I think I have docker properly installed and build complete, but I get the following message when I try to analyze the sample data. Any suggestions on how to proceed?

Joels-MacBook:open_dbm-master joelthomas$ bash process_dbm.sh --input_path=/Users/joelthomas/Documents_Backup/Documents/Emory/Research Activities/Digital Biomarkers/open_dbm-master/sample_data --output_path=/Users/joelthomas/Desktop

Usage: process_dbm.sh --input_path parameterA --output_path parameterB --dbm_group parameterC
	--input_path Description of what is parameterA
	--output_path Description of what is parameterB
	-dbm_group Description of what is parameterC
Joels-MacBook:open_dbm-master joelthomas$ bash process_dbm.sh --input_path=/Users/joelthomas/Documents_Backup/Documents/Emory/Research Activities/Digital Biomarkers/open_dbm-master/sample_data --output_path=/Users/joelthomas/Desktop --dbm_group=acoustic

Usage: process_dbm.sh --input_path parameterA --output_path parameterB --dbm_group parameterC
	--input_path Description of what is parameterA
	--output_path Description of what is parameterB
	-dbm_group Description of what is parameterC

**Comment by anzarabbas** [comment]
Hey @joelgthomas, it seems like there's a space in your input file path in the "Digital Biomarkers" folder name.
Try addressing that and running again. Let me know if that doesn't work, though.
