### ISSUE TITLE
Unable to Build OpenDBM Docker Images

### ISSUE THREAD

**Issue by tsharma3427** [AiCure/open_dbm#54]
### Bug Type

Build/Install

### Source

source (default)

### OpenDBM Version

2.0

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey v 12.4

### Python version

3.9.13

### Docker version

20.10.22

### 🐞 Describe the bug. Steps/Code to Reproduce

**_This is from the Dockerfile when attempting to run "docker build --tag dbm ."_**

RUN ln -sfn /usr/bin/pip3 /usr/bin/pip

COPY . /app

#cloning openface
WORKDIR /app/opendbm/pkg
RUN git clone https://github.com/AiCure/open_dbm.git -b openface

RUN echo "Installing OpenFace..."
WORKDIR /app/opendbm/pkg/open_dbm/OpenFace
RUN bash ./download_models.sh
RUN dpkg --configure -a
RUN su -c ./install.sh
RUN echo "Done OpenFace!"

### Expected Results

It would successfully build "dbm" image in the docker.

### Actual Results and relevant log outputs

 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.67kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04            0.7s
 => [auth] library/ubuntu:pull token for registry-1.docker.io              0.0s
 => [stage-1  1/22] FROM docker.io/library/ubuntu:18.04@sha256:c1d0baf242  0.0s
 => [internal] load build context                                         20.3s
 => => transferring context: 1.96GB                                       20.3s
 => CACHED [stage-1  2/22] RUN apt-get update && apt-get install -y pytho  0.0s
 => CACHED [stage-1  3/22] RUN ln -sfn /usr/bin/pip3 /usr/bin/pip          0.0s
 => [stage-1  4/22] COPY . /app                                            4.5s
 => [stage-1  5/22] WORKDIR /app/opendbm/pkg                               0.0s
 => ERROR [stage-1  6/22] RUN git clone https://github.com/AiCure/open_db  0.4s

------                                                                          
 > [stage-1  6/22] RUN git clone https://github.com/AiCure/open_dbm.git -b openface:
#11 0.200 Cloning into 'open_dbm'...
#11 0.430 fatal: Remote branch openface not found in upstream origin

------
executor failed running [/bin/sh -c git clone https://github.com/AiCure/open_dbm.git -b openface]: exit code: 128

**Comment by shptk** [comment]
@tsharma3427 This has happened as there is no branch by the name "openface" you are asking the Dockerfile to clone. Give a valid branch name that exists in this repository

**Comment by shptk** [comment]
@haposan06 I think this issue can be closed now.

**Comment by tsharma3427** [comment]
Yup I fixed this issue a year ago. The developers should update the code as well so people don't have issues with it in the future - if you all make updates to the code, the onus shouldn't have to be on the user to fix said code.
